<?php

return [
    "backup_already_created" => 'Sicherung bereits erstellt',
    'cannot_delete_account' => 'Konto kann derzeit nicht gelöscht werden.',
    'cannot_delete_backup' => 'Sicherung kann nicht gelöscht werden',
    'cannot_compare_database_changes' => 'Datenbankänderungen können nicht verglichen werden.',
    'cannot_connect_to_url' => 'Keine Verbindung zur URL.',
    'cannot_connect_to_ftp' => 'Verbindung zum FTP-Server nicht möglich',
    'cannot_generate_subdomain_for_instance' => 'Subdomain für importierte Instanz kann nicht generiert werden',
    'cannot_retry_installation' => 'Installation in dieser Instanz kann nicht wiederholt werden.',
    'domain_name_not_available' => 'Der Domainname ist nicht verfügbar',
    'domain_exists' => 'Domain existiert bereits',
    'domain_ssl_order_in_progress' => 'Domain hat bereits SSL-Bestellung in Bearbeitung',
    'invalid_domain' => 'Ungültige Domain',
    'invalid_value' => 'Ungültiger Wert',
    'invalid_value_with_item' => 'Ungültiger Wert :item',
    'invalid_token' => 'Ungültiges Token',
    'invalid_request' => 'Ungültige Anfrage',
    'invalid_php_version' => 'Ungültige PHP-Version',
    'invalid_protocol' => 'Invalid protocol',
    'invalid_frequency_settings' => 'Ungültige Frequenzeinstellungen',
    "incorrect_credentials" => "Die eingegebenen Zugangsdaten sind nicht korrekt. Bitte versuchen Sie es erneut.",
    'invitation_sent' => 'Einladung wurde an :email gesendet',
    'invitation_cannot_yourself' => 'Kann sich nicht einladen',
    'invitation_resent' => 'Du kannst die Einladung erneut senden :time',
    'label_exists' => 'Label existiert bereits',
    'label_in_use' => 'Bezeichnung in Verwendung',
    'label_not_found' => 'Label nicht gefunden',
    'limit_reached' => 'Limit erreicht.',
    "no_more_accounts" => "Dienst kann nicht mehr Hosting Konten haben.",
    "no_server_with_criteria" => "Kann die Kriterien des Server nicht finden",
    "instance_not_staging" => "Die Instanz stagniert.",
    'required_parent_domain' => 'Eltern-Domain erforderlich',
    'required_value' => 'Erforderlicher Wert',
    'staging_cannot_shared_directly' => 'Staging-Instanzen können nicht direkt auf freigegeben werden',
    "sort_possible_values" => "Mögliche Werte sind: asc,desc",
    'sso_generate_token_limit' => 'Sie können SSO-Token einmal alle 5 Sekunden generieren.',
    'wordpress_not_found' => 'Wordpress nicht im Pfad :path gefunden',
    'too_weak_password' => 'Passwort zu schwach',
    'cannot_connect_to_integration' => 'Konnte die Integration nicht erfolgreich verbinden. Bitte überprüfen Sie, ob die angegebenen Details korrekt sind.',
    'invalid_email_domain' => 'Ungültige E-Mail-Domäne',
    'not_allowed_dns_record_type' => 'Datensatztyp ist nicht zulässig.',
    'invalid_dns_server' => 'Ungültiger DNS-Server',
    'cannot_delete_service_with_existing_instances' => 'Dienst mit existierenden Instanzen kann nicht gelöscht werden.',
    'import_files_required' => 'Importieren von Dateien erforderlich.',
];
